apiVersion: v1
kind: Pod
metadata:
  name: nginxpodfromagrocd
  labels:
    run: pod
spec:
  containers:
  - image: nginx
    name: pod
    resources : {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
